debug:
  verbose: True            # Whether to log information and warnings
  
  # Enable or disable subsystems for testing
  enable_perception: True
  enable_manipulation: True
  enable_end_effector: True
  enable_external_mechanisms: True 
  enable_navigation: True

sensor:
  sensor_fail_threshold: 3 # Number of consecutive sensor fails before replacement

gripper:
  replacement: manual      # Manual or automatic replacement of the sensor (auto / manual)