debug:
  verbose: True                 # Whether to log information and warnings
  
  # Enable or disable subsystems for testing
  enable_perception: False
  enable_manipulation: True
  enable_end_effector: True
  enable_external_mechanisms: False 
  enable_navigation: False 

  enable_fake_perception: False # For testing purposes, create a fake cornstalk detection
  enable_arc_corn: True
  enable_replacement: True

sensor:
  sensor_fail_threshold: 2      # Number of consecutive sensor fails before replacement

gripper:
  replacement: auto             # Manual or automatic replacement of the sensor (auto / manual)
  clean_extend: False            # Whether to extend the linear actuator for cleaning and calibrating